Add Overlapping Community Leaderboards to PSI Section
cursive-team/connections pull request #174
Opened 2024-11-05 17:30 UTC by stevenelleman

If there are shared communities AND top 10 leaderboard entries: 
<img width="430" alt="Screenshot 2024-11-06 at 12 17 12 AM" src="https://github.com/user-attachments/assets/ee90d3e4-6a25-4211-aec9-0ba8cb341d53">

If there are no shared communities OR no top 10 leaderboard entries: 
<img width="431" alt="Screenshot 2024-11-06 at 12 16 15 AM" src="https://github.com/user-attachments/assets/91930774-0ceb-4f5f-8f1b-4a8f3166c4a4">

2024-11-05 21:12 UTC, stevenelleman commented on apps/frontend/src/pages/people/[username].tsx
> +  "STRAVA_PREVIOUS_MONTH_RUN_DISTANCE": "running distance over last month",
*distance running over last month

2024-11-05 21:13 UTC, stevenelleman commented on apps/frontend/src/pages/profile/overview.tsx
> +            {`${user?.userData.username}`}
In one location we had username at the top and display below it, and two cases with the reverse. Given that quite a few users have not filled out the display name, and username is required, I swapped the naming to consistently put username first and display name below it.

2024-11-05 21:14 UTC, stevenelleman commented on packages/types/src/chip/index.ts
> +]
Going to sleep on this, whether it should be shared or not.

2024-11-08 18:44 UTC, AndrewCLu commented on apps/frontend/src/pages/people/[username].tsx
> +            case ChipIssuer.EDGE_CITY_LANNA:
do we have devcon leaderboards set up?

2024-11-08 18:46 UTC, AndrewCLu approved these changes
approved pending testing with lanna + devcon leaderboards

2024-11-08 23:06 UTC, stevenelleman commented on apps/frontend/src/pages/people/[username].tsx
> +          let leaderboardTypes: LeaderboardEntryType[] = SharedLeaderboards;
Shared between the two users, I'll change name to "SharedIssuerLeaderboards"

2024-11-09 12:32 UTC, RiverRuby requested changes
Don't merge until I get to update copy+styling later

2024-11-09 12:32 UTC, RiverRuby commented on apps/frontend/src/pages/people/[username].tsx
> +                            const message = `#${entry.position} for ${board} at ${name}.`;
I want to clean up this copy + styling

2024-12-06 06:23 UTC, closed without merging

2024-12-06 06:24 UTC, RiverRuby commented
Closing since this is outdated and unclear that we want this for now. Discovering overlapping communities won't be useful until we have many more communities.

2024-12-06 16:22 UTC, stevenelleman commented
> Closing since this is outdated and unclear that we want this for now. Discovering overlapping communities won't be useful until we have many more communities.

@RiverRuby the point of this was to surface leaderboard on tap (ie if you're top 10 on github contributions, it's surfaced), but if you do that you need to handle the case where you have multiple communities. The multiple community aspect is secondary.